[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mysqli"]

[phases.install]
cmds = ["mkdir -p /etc/nginx"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t public"
